export interface ModuleEntry {
  key: string;
  label: string;
}

export interface ModuleGroup {
  group: string;
  items: ModuleEntry[];
}

export const MODULE_CATALOG: ModuleGroup[] = [
  {
    group: "Dashboard & Front Office",
    items: [
      { key: "/", label: "Dashboard" },
      { key: "/patients", label: "Patients" },
      { key: "/billing-desk", label: "Billing Desk" },
      { key: "/estimations", label: "Estimations" },
      { key: "/referrals", label: "Referral Doctors" },
      { key: "/consultants", label: "Consultants on Job" },
      { key: "/entities", label: "Entities" },
    ],
  },
  {
    group: "Clinical",
    items: [
      { key: "/doctor", label: "Doctor Dashboard" },
      { key: "/doctors", label: "Doctors Master" },
      { key: "/opd", label: "OPD" },
      { key: "/ipd", label: "IPD" },
      { key: "/wards", label: "Wards" },
      { key: "/diagnostics", label: "Pathology / Radiology" },
      { key: "/ot", label: "Operation Theatre" },
      { key: "/consent-forms", label: "Consent Forms" },
      { key: "/discharge-summary", label: "Discharge Summary" },
      { key: "/insurance", label: "TPA / Insurance" },
    ],
  },
  {
    group: "Pharmacy & Stores",
    items: [
      { key: "/pharmacy/command-center", label: "Pharmacy Command Center" },
      { key: "/pharmacy", label: "Pharmacy (Sales & Stock)" },
      { key: "/pharmacy/dashboard", label: "Pharmacy Dashboard" },
      { key: "/pharmacy/prescription-queue", label: "Prescription Queue" },
      { key: "/pharmacy/ward-stock", label: "Ward / ICU Stock" },
      { key: "/pharmacy/ipd-ledger", label: "IPD Medicine Ledger" },
      { key: "/pharmacy/mar", label: "MAR (Medication Admin Record)" },
      { key: "/pharmacy/kits", label: "OT / Procedure Kits" },
      { key: "/pharmacy/implants", label: "Implant Tracking" },
      { key: "/pharmacy/stock-verification", label: "Stock Verification" },
      { key: "/pharmacy/expiry-loss", label: "Expiry Loss Register" },
      { key: "/pharmacy/staff-issue", label: "Staff / Internal Issue" },
      { key: "/pharmacy/purchase-indent", label: "Purchase Indents" },
      { key: "/pharmacy/analytics", label: "Pharmacy Analytics" },
      { key: "/pharmacy/rate-history", label: "MRP / Rate History" },
      { key: "/pharmacy/pediatric-safety", label: "Pediatric Dose Safety" },
      { key: "/pharmacy/insurance-billing", label: "Insurance / TPA Billing" },
      { key: "/pharmacy/patient-returns", label: "Patient Returns (Enhanced)" },
      { key: "/pharmacy/credit-limits", label: "Patient Credit Limits" },
      { key: "/pharmacy/rate-contracts", label: "Vendor Rate Contracts" },
      { key: "/pharmacy/gst-reconciliation", label: "GST Reconciliation" },
      { key: "/pharmacy/tally-export", label: "Tally / Accounting Export" },
      { key: "/pharmacy/stock-heatmap", label: "Stock Heatmap" },
      { key: "/pharmacy/counselling-slip", label: "Counselling Slips" },
      { key: "/pharmacy/fraud-monitor", label: "Fraud Monitor (Admin)" },
      { key: "/pharmacy/sales-returns", label: "Sales Returns" },
      { key: "/pharmacy/purchase-returns", label: "Purchase Returns" },
      { key: "/pharmacy/expiry", label: "Expiry Management" },
      { key: "/pharmacy/reorder", label: "Reorder Suggestions" },
      { key: "/pharmacy/schedule-h-register", label: "Schedule H Register" },
      { key: "/pharmacy/ndps-register", label: "NDPS Register" },
      { key: "/pharmacy/shift-closing", label: "Shift Closing" },
      { key: "/pharmacy/audit-log", label: "Pharmacy Audit Log" },
      { key: "/inventory", label: "Inventory" },
      { key: "/indents", label: "Hospital Indents" },
      { key: "/vendors", label: "Vendors" },
    ],
  },
  {
    group: "Billing & Accounts",
    items: [
      { key: "/billing", label: "Billing" },
      { key: "/discounts", label: "Discounts" },
      { key: "/accounting", label: "Accounting" },
      { key: "/accounting/banks", label: "Bank Details" },
      { key: "/accounting/ledgers", label: "Ledger Master" },
      { key: "/bank-reconciliation", label: "Bank Reconciliation" },
      { key: "/collection-report", label: "Collection Report" },
    ],
  },
  {
    group: "Reports",
    items: [
      { key: "/reports", label: "Reports Home" },
      { key: "/reports/hospital-stats", label: "Hospital Statistics" },
      { key: "/reports/ipd", label: "IPD Reports" },
      { key: "/reports/opd", label: "OPD Reports" },
      { key: "/reports/pharmacy", label: "Pharmacy Reports" },
      { key: "/reports/finance", label: "Finance Reports" },
      { key: "/reports/stock", label: "Stock Reports" },
      { key: "/reports/patient-ledger", label: "Patient Ledger" },
      { key: "/reports/gst", label: "GST Summary" },
      { key: "/reports/doctor-performance", label: "Doctor Performance" },
      { key: "/reports/department-revenue", label: "Department-wise Revenue" },
    ],
  },
  {
    group: "Masters & Admin",
    items: [
      { key: "/documents", label: "Documents" },
      { key: "/masters/demographic", label: "Patient Demographics" },
      { key: "/prescription-templates", label: "Prescription Templates" },
      { key: "/employees", label: "Employees & Roles" },
      { key: "/billing-heads", label: "Billing Heads" },
      { key: "/packages", label: "Health Packages" },
      { key: "/settings", label: "Hospital Settings" },
      { key: "/permissions", label: "Permissions Manager" },
    ],
  },
];

export const ALL_MODULE_KEYS: string[] = MODULE_CATALOG.flatMap((g) => g.items.map((i) => i.key));

export const MODULE_LABELS: Record<string, string> = Object.fromEntries(
  MODULE_CATALOG.flatMap((g) => g.items.map((i) => [i.key, i.label] as const)),
);

export const ROLES = [
  { value: "admin", label: "Admin" },
  { value: "doctor", label: "Doctor" },
  { value: "nurse", label: "Nurse" },
  { value: "receptionist", label: "Receptionist" },
  { value: "cashier", label: "Cashier / Billing" },
  { value: "lab_tech", label: "Lab Technician" },
  { value: "radiology_tech", label: "Radiology Tech" },
  { value: "pharmacist", label: "Pharmacist" },
  { value: "house_keeping", label: "Housekeeping" },
] as const;

export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  admin: ALL_MODULE_KEYS,
  doctor: [
    "/", "/patients", "/doctor", "/estimations", "/referrals", "/consultants",
    "/opd", "/ipd", "/doctors", "/diagnostics", "/ot", "/consent-forms",
    "/discharge-summary", "/wards", "/discounts", "/documents",
    "/masters/demographic", "/prescription-templates",
    "/reports", "/reports/ipd", "/reports/opd", "/reports/doctor-performance",
  ],
  nurse: [
    "/", "/patients", "/ipd", "/wards", "/diagnostics", "/ot", "/consent-forms",
    "/discharge-summary", "/indents", "/documents", "/masters/demographic",
    "/reports", "/reports/ipd", "/reports/opd",
  ],
  receptionist: [
    "/", "/patients", "/billing-desk", "/estimations", "/referrals", "/consultants",
    "/opd", "/ipd", "/doctors", "/consent-forms", "/packages", "/documents",
    "/masters/demographic",
    "/reports", "/reports/hospital-stats", "/reports/ipd", "/reports/opd",
    "/reports/patient-ledger",
  ],
  cashier: [
    "/", "/patients", "/billing-desk", "/billing", "/discounts", "/estimations",
    "/referrals", "/consultants", "/opd", "/ipd", "/insurance", "/packages",
    "/pharmacy", "/accounting/banks", "/collection-report",
    "/masters/demographic",
    "/reports", "/reports/opd", "/reports/pharmacy", "/reports/finance",
    "/reports/patient-ledger", "/reports/department-revenue",
  ],
  lab_tech: [
    "/", "/diagnostics", "/masters/demographic",
  ],
  radiology_tech: [
    "/", "/diagnostics", "/masters/demographic",
  ],
  pharmacist: [
    "/",
    "/pharmacy/command-center",
    "/pharmacy", "/pharmacy/dashboard",
    "/pharmacy/prescription-queue",
    "/pharmacy/ward-stock",
    "/pharmacy/ipd-ledger",
    "/pharmacy/mar",
    "/pharmacy/kits",
    "/pharmacy/implants",
    "/pharmacy/stock-verification",
    "/pharmacy/expiry-loss",
    "/pharmacy/staff-issue",
    "/pharmacy/purchase-indent",
    "/pharmacy/analytics",
    "/pharmacy/rate-history",
    "/pharmacy/sales-returns",
    "/pharmacy/purchase-returns",
    "/pharmacy/expiry",
    "/pharmacy/reorder",
    "/pharmacy/schedule-h-register",
    "/pharmacy/ndps-register",
    "/pharmacy/shift-closing",
    "/pharmacy/audit-log",
    "/pharmacy/pediatric-safety",
    "/pharmacy/insurance-billing",
    "/pharmacy/patient-returns",
    "/pharmacy/credit-limits",
    "/pharmacy/rate-contracts",
    "/pharmacy/gst-reconciliation",
    "/pharmacy/tally-export",
    "/pharmacy/stock-heatmap",
    "/pharmacy/counselling-slip",
    "/pharmacy/barcode-scan",
    "/pharmacy/pmjay-claims",
    "/pharmacy/drug-licences",
    "/pharmacy/consignment-stock",
    "/pharmacy/abc-ved-fsn",
    "/pharmacy/vendor-schemes",
    "/pharmacy/kpi-scorecard",
    "/inventory", "/indents", "/vendors",
    "/masters/demographic",
    "/reports", "/reports/pharmacy", "/reports/stock",
  ],
  house_keeping: ["/"],
};
